config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'test#index'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :saxophones, concerns: :paginatable
  resources :violins, concerns: :paginatable
  resources :guitars, concerns: :paginatable
  resources :pianos, concerns: :paginatable

  resources :users, only: [:show]

  resources :about, only: [:index]

  resources :products, only: [:show] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :questions, only: [:index]

  resources :cart, only: [:index]

  scope path_names: { new: 'new_message',
                      create: 'create_message',
                      index: 'support' } do
    resources :messages, path: 'support', only: [:index, :new, :create]
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  product_id :integer
#
# Comment model
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  auto_html_for :body do
    html_escape
    image(width: 250, height: 250)
    youtube(width: 400, height: 250, autoplay: false)
    link target: '_blank', rel: 'nofollow'
    simple_format
  end

  validates :body, presence: true, length: { maximum: 5000 }
  validates :user_id, :product_id, presence: true, numericality:
            { greater_than: 0, only_integer: true }

  # Method for displaying comment's id, user's full
  # name and product name in AdminPanel. ActiveAdmin
  # uses the `display_name` method in models for its
  # drop-down inputs.
  def display_name
    id.to_s + '. From: ' + user.first_name + ' ' +
      user.last_name + '. On: ' + product.name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @product, notice: 'Comment Created!'
    else
      redirect_to @product, notice: 'Something went wrong...'
    end
  end

  def show
  end

  def edit
    @product = Product.find(params[:product_id])
    @comment = @product.comments.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @comment = @product.comments.find(params[:id])
    respond_to do |format|
      if @comment.update_attributes(comment_params)
        format.html { redirect_to @comment.product, notice: 'Comment Updated!' }
      else
        format.html do
          redirect_to @comment.product, notice: 'Something went wrong...'
        end
      end
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @comment = @product.comments.find(params[:id])
    @comment.destroy!
    redirect_to @product, notice: 'Comment Deleted!'
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.erb
<div class="message-item" id="m<%= comment.id %>">
    <div class="message-inner">
        <div class="message-head clearfix">
            <div class="avatar pull-left">
                <%= link_to product_path(@product) do %>
                    <%= gravatar_tag comment.user.email, size: 40 %>
                <% end %>
            </div>
            <div class="user-detail">
                <h5 class="handle"><%= comment.user.full_name %></h5>
                <div class="post-meta">
                    <div class="asker-meta">
                        <span class="qa-message-what"></span>
                        <span class="qa-message-when">
                            <span class="qa-message-when-data">
                                <%= time_ago_in_words(comment.created_at) %> ago
                            </span>
                        </span>
                        <span class="qa-message-who">
                            <span class="qa-message-who-pad">by </span>
                            <span class="qa-message-who-data">
                                <%= link_to comment.user.full_name, product_path(@product) %>
                            </span>
                        </span>
                    </div>
                </div>
                <div class="pull-right edit-comment-controls">
                    <%= link_to edit_product_comment_path(comment.product, comment), class: 'control-links' do %>
                        <span class="glyphicon glyphicon-pencil"></span>
                    <% end %>
                    <%= link_to [comment.product, comment], method: :delete do %>
                        <span class="glyphicon glyphicon-remove"></span>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="qa-message-content">
            <%= raw(comment.body_html) %>
        </div>
</div></div>

app/views/comments/_form.html.erb
<div class="container">
  <%= simple_form_for([@comment.product_id, @comment], url: product_comment_path(@comment.product_id, @comment)) do |f| %>
    <div class="panel panel-info">
      <div class="panel-heading">Edit comment</div>
      <div class="panel-body">
        <%= f.error_notification %>
        <%= f.input :body, required: true, placeholder: 'Type in your comment...', input_html: { class: 'form-control'}, label: false %>
      </div>
      <div class="panel-footer">
        <%= f.button :submit, class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>