config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'test#index'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :saxophones, concerns: :paginatable
  resources :violins, concerns: :paginatable
  resources :guitars, concerns: :paginatable
  resources :pianos, concerns: :paginatable

  resources :users, only: [:show]

  resources :about, only: [:index]

  resources :products, only: [:show] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :questions, only: [:index]

  resources :cart, only: [:index]

  scope path_names: { new: 'new_message',
                      create: 'create_message',
                      index: 'support' } do
    resources :messages, path: 'support', only: [:index, :new, :create]
  end
end

app/views/layouts/_ad_navbar_item.html.erb
<div class="item <%= if i == 0 then 'active' end %>">
  <a href="#"><img src="http://placehold.it/254x150/3498db/f5f5f5/&text=<%= item.products_category.name %>" class="img-responsive" alt='<%= item.name %>'></a>
  <h4><small><%= shorten(item, 50) %></small></h4>
  <button class="btn btn-primary" type="button"><%= to_price(item) %></button>
  <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-shopping-cart"></span> Add to Cart</button>
</div>

app/views/layouts/_footer.html.erb
<footer class="bottom-footer text-center">
    <hr>
    <div class="row">
        <div class="col-lg-12">
            <ul class="nav nav-justified">

                <li>
                    <div class="container">
                      <p class="navbar-text pull-left brand-name">
                        <%= link_to 'Symphony © 2015', root_path %>
                      </p>

                      <a href="#" class="navbar-btn btn-danger btn pull-right">
                      <span class="glyphicon glyphicon-envelope"></span>  Subscribe to our Newsletter</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<div class="main-navbar">
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="js-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand">Symphony</a>
    </div>

    <!--"Browse the Store" DROPDOWN -->
    <div class="collapse navbar-collapse js-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown mega-dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse The Store<span class="glyphicon glyphicon-chevron-down"></span></a>
          <ul class="dropdown-menu mega-dropdown-menu row">
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">New in Symphony</li>
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                                  <% @ad_instruments.each_with_index do |item, i| %>
                                    <%= render partial: 'layouts/ad_navbar_item',
                                               locals: { item: item, i: i } %>
                                  <% end %>
                  </div><!-- End Carousel Inner -->
                </div><!-- /.carousel -->
                <li class="divider"></li>
                <li>
                  <%= link_to root_path do %>
                    View all Instruments <span class="glyphicon glyphicon-chevron-right pull-right"></span>
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Violins</li>
                <% @instruments[:violins][0...4].each do |v| %>
                  <li>
                    <%= link_to v.company, violins_path %>
                  </li>
                <% end %>
                <li class="divider"></li>
                <li class="dropdown-header">Pianos</li>
                <% @instruments[:pianos][0...4].each do |p| %>
                  <li>
                    <%= link_to p.company, pianos_path %>
                  </li>
                <% end %>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Guitars</li>
                <% @instruments[:guitars][0...4].each do |g| %>
                  <li>
                    <%= link_to g.company, guitars_path %>
                  </li>
                <% end %>
                <li class="divider"></li>
                <li class="dropdown-header">Saxophones</li>
                <% @instruments[:saxophones][0...4].each do |s| %>
                  <li>
                    <%= link_to s.company, saxophones_path %>
                  </li>
                <% end %>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Support</li>
                <li><%= link_to 'About', about_index_path %></li>
                <li><%= link_to 'Delivery Info', about_index_path %></li>
                <li><%= link_to 'FAQ & Help', about_index_path %></li>
                <li><%= link_to 'Contacts', about_index_path %></li>
                <li class="divider"></li>
                <li class="dropdown-header">Newsletter</li>
                <form class="form" role="form">
                  <div class="form-group">
                    <label class="sr-only" for="email">Email address</label>
                    <input type="email" class="form-control" id="email" placeholder="Enter email">
                  </div>
                  <button type="submit" class="btn btn-primary btn-block">Subscribe</button>
                </form>
              </ul>
            </li>
          </ul>
        </li>
      </ul>  <!--END "Browse the Store" DROPDOWN -->


    <!-- ======================= -->
    <%- if user_signed_in? %>

      <ul class="nav navbar-nav navbar-right">
        <li class="about-link"><%= link_to 'Support', messages_path %></li>
        <li class="about-link"><%= link_to 'About', about_index_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= gravatar_tag current_user.email, size: 30, secure: true, html: { class: 'small-gravatar'} %>      <%= current_user.full_name %> (₴194000)<span class="glyphicon glyphicon-chevron-down"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', user_path(current_user.id) %></li>
              <li><%= link_to 'Shopping Cart (₴194000)', cart_index_path %></li>
              <li><%= link_to 'Settings', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
      </ul> <!-- ========== END (LOGIN) JOHN SMITH PROFILE ============= -->


      <!-- ======= START SEARCH ========== -->
      <form class="navbar-form" role="search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search">
          <span class="input-group-btn">
              <button type="reset" class="btn btn-default">
                <span class="glyphicon glyphicon-remove">
                  <span class="sr-only">Close</span>
          </span>
          </button>
          <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search">
                  <span class="sr-only">Search</span>
            </span>
          </button>
          </span>
        </div>
      </form>
      <!-- === END SEARCH === -->

    <% else %>
    <!-- LOGIN START -->
      <ul class="nav navbar-nav navbar-right">
        <li class="about-link"><%= link_to 'About', about_index_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle not-signed-in" data-toggle="dropdown"><b>Login</b> <span class="glyphicon glyphicon-chevron-down"></span></a>
          <ul id="login-dp" class="dropdown-menu">
            <li>
               <div class="row">
                  <div class="col-md-12">
                    Login via
                    <div class="social-buttons">
                      <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
                      <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
                    </div>
                    <div class="social-buttons">
                      <a href="#" class="btn btn-gh"><i class="fa fa-github"></i> Github</a>
                      <a href="#" class="btn btn-gp"><i class="fa fa-google-plus"></i> Google+</a>
                    </div>
                                    or

        <%= simple_form_for(resource, as: resource_name,
                                        url: session_path(resource_name),
                                        wrapper_mappings: { boolean: :vertical_boolean },
                                        html: { class: "form login-tab", id: "login-nav",
                                                role: "form" }) do |f| %>
            <div class="form-group">
              <%= f.input :email, placeholder: "Email address", required: true, autofocus: true, label: false, input_html: { class: 'form-control' } %>
            </div>

            <div class="form-group">
              <%= f.input :password, placeholder: "Password", required: true, label: false, input_html: { class: 'form-control' } %>
            </div>
            <div class="checkbox">
               <label>
                <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
               </label>
            </div>
            <div class="form-group">
               <%= f.button :submit, "Log in", class: "btn btn-primary btn-block" %>
              <div class="help-block text-right"><%= link_to "Forgot your password?", new_password_path(resource_name) %></div>
            </div>
        <% end %>
                  </div>
                  <div class="bottom text-center">
                    New here? <a href="#"><b><%= link_to 'Join Us', new_user_registration_path %></b></a>
                  </div>
               </div>
            </li>
          </ul>
        </li>
      </ul> <!-- LOGIN END -->

      <!-- ======= START SEARCH ========== -->
      <form class="navbar-form" role="search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search">
          <span class="input-group-btn">
              <button type="reset" class="btn btn-default">
                <span class="glyphicon glyphicon-remove">
                  <span class="sr-only">Close</span>
          </span>
          </button>
          <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search">
                  <span class="sr-only">Search</span>
            </span>
          </button>
          </span>
        </div>
      </form>
      <!-- === END SEARCH === -->


      <% end %>
    </div><!-- /.nav-collapse -->
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyBursaTeamProject</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield(:head) %>
  <%= render 'layouts/header' %>
  <div class="container">

    <% messages = [] %>
    <% flash.each do |type, message| %>
        <% messages << message %>
    <% end %>
    <%= notify('info', messages, 'bottom-left', '4000') %>

    <%= yield %>

    <%= render 'layouts/footer' unless @disable_footer %>

  </div>
</body>
</html>